#!/bin/sh

[ "${ACTION}" = "released" ] || exit 0

. /lib/functions.sh

logger "$BUTTON pressed for $SEEN seconds"

if [ "$SEEN" -lt 1 ]
then
	echo "BUTTON TRIGGERED REBOOT" > /dev/console
	sync
	reboot
elif [ "$SEEN" -gt 5 ]
then
	echo "BUTTON TRIGGERED FACTORY RESET" > /dev/console
	jffs2reset -y && reboot &
fi

return 0
